spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: house_api_db
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml


